/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author sauld
 */
public class ConfirmLlegada extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfirmLlegada
     */
    private static Controlador.dao.EventoImp event = null;

    public ConfirmLlegada() {
        initComponents();
        this.setLocation(55, 45);
        event = new Controlador.dao.EventoImp();

    }
   public void confir(java.awt.event.MouseEvent evt){
       int a = JTableInvitacion.getSelectedRow();
   if (evt.getClickCount() == 2) {
       if (a >= 0)
           event.ConfirmarLLegada(Integer.parseInt(JTableInvitacion.getValueAt(a, 0)
                   .toString()), Integer.parseInt(IDevento.getText()));
        }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableInvitacion = new javax.swing.JTable();
        BusquedaInvitacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnInvitacion = new javax.swing.JButton();
        NombreDelEvento = new javax.swing.JLabel();
        IDevento = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CantidadFaltante = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel7MouseMoved(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTableInvitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Ubicacion", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        JTableInvitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableInvitacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JTableInvitacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JTableInvitacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTableInvitacionMousePressed(evt);
            }
        });
        JTableInvitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTableInvitacionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(JTableInvitacion);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 610, 190));

        BusquedaInvitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaInvitacionActionPerformed(evt);
            }
        });
        BusquedaInvitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BusquedaInvitacionKeyReleased(evt);
            }
        });
        jPanel7.add(BusquedaInvitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 320, 30));

        jLabel12.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel12.setText("Buscar : ");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jPanel8.setBackground(new java.awt.Color(0, 120, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 0), null));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 2, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirmar LLegada");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icon (2).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        btnInvitacion.setBackground(new java.awt.Color(0, 120, 153));
        btnInvitacion.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        btnInvitacion.setText("Confirmar Llegada");
        btnInvitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitacionActionPerformed(evt);
            }
        });
        jPanel7.add(btnInvitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 180, 30));

        NombreDelEvento.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        NombreDelEvento.setText("Nombre Evento");
        NombreDelEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(NombreDelEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 260, 30));

        IDevento.setText("ID");
        jPanel7.add(IDevento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 20, 20));

        jButton4.setBackground(new java.awt.Color(0, 120, 153));
        jButton4.setFont(new java.awt.Font("Modern No. 20", 0, 15)); // NOI18N
        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, 30));

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad Faltante por llegar :");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        CantidadFaltante.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        CantidadFaltante.setForeground(new java.awt.Color(204, 0, 0));
        CantidadFaltante.setText("Cantidad Faltante por llegar");
        jPanel7.add(CantidadFaltante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTableInvitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableInvitacionMouseClicked
        confir(evt);
    }//GEN-LAST:event_JTableInvitacionMouseClicked

    private void JTableInvitacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableInvitacionMouseEntered

    }//GEN-LAST:event_JTableInvitacionMouseEntered

    private void JTableInvitacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableInvitacionMouseExited
        // TODO add your handling code here:
        event.UserNoConfir(JTableInvitacion, Integer.parseInt(IDevento.getText()));

    }//GEN-LAST:event_JTableInvitacionMouseExited

    private void JTableInvitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableInvitacionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTableInvitacionMousePressed

    private void JTableInvitacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTableInvitacionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTableInvitacionKeyPressed

    private void BusquedaInvitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaInvitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaInvitacionActionPerformed

    private void BusquedaInvitacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaInvitacionKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_BusquedaInvitacionKeyReleased

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnInvitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitacionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnInvitacionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vistas.PMenu.jInternalFrame2.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField BusquedaInvitacion;
    private static javax.swing.JLabel CantidadFaltante;
    public static javax.swing.JLabel IDevento;
    public static javax.swing.JTable JTableInvitacion;
    public static javax.swing.JLabel NombreDelEvento;
    private javax.swing.JButton btnInvitacion;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
