/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.dao.EventoImp;
import Modelo.EventoModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static Vistas.PMenu.JTableEvento;


/**
 *
 * @author sauld
 */
public class PeventosInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form PeventosInternal
     */

    public static Controlador.dao.EventoImp event = null;
    public static Modelo.EventoModel evenMode = null;

    public PeventosInternal() {

        initComponents();
        this.setLocation(190, 40);
        event = new EventoImp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor. * WARNING: Do NOT modify this code. The
     * content of this method is always
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEventoMante = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreEvento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        UbicacionEvento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FechaEvento = new javax.swing.JTextField();
        AgregarEvento = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        EditarEvento = new javax.swing.JButton();
        TipoEvento = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanelEventoMante.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelEventoMante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nombre: ");
        jPanelEventoMante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanelEventoMante.add(nombreEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 261, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fecha:");
        jPanelEventoMante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanelEventoMante.add(UbicacionEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 261, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tipo:");
        jPanelEventoMante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Direccion:");
        jPanelEventoMante.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanelEventoMante.add(FechaEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 261, 32));

        AgregarEvento.setBackground(new java.awt.Color(0, 120, 153));
        AgregarEvento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgregarEvento.setForeground(new java.awt.Color(255, 255, 255));
        AgregarEvento.setText("Agregar");
        AgregarEvento.setEnabled(false);
        AgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEventoActionPerformed(evt);
            }
        });
        jPanelEventoMante.add(AgregarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 40));

        jButton4.setBackground(new java.awt.Color(0, 120, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelEventoMante.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 120, 40));

        EditarEvento.setBackground(new java.awt.Color(0, 120, 153));
        EditarEvento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EditarEvento.setForeground(new java.awt.Color(255, 255, 255));
        EditarEvento.setText("Editar");
        EditarEvento.setEnabled(false);
        EditarEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarEventoMouseClicked(evt);
            }
        });
        EditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEventoActionPerformed(evt);
            }
        });
        jPanelEventoMante.add(EditarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 130, 40));

        TipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hola" }));
        jPanelEventoMante.add(TipoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 260, 40));

        jPanel2.setBackground(new java.awt.Color(0, 120, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mantenimiento Evento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEventoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEventoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void UpdateShow() {
        int a = JTableEvento.getSelectedRow();

        if (a >= 0) {
            // if (nombreEvento.getText().length() >= 1 && FechaEvento.getText().length() > 1 && 1 <= UbicacionEvento.getText().length()) {
            
           PMenu.btnShow();
            //Esto es para desabilitar los botones que no son necesarion para esta opcion
             AgregarEvento.setEnabled(false);
            EditarEvento.setEnabled(true);
            //Esto es para desabilitar los botones que no son necesarion para esta opcion
           
            nombreEvento.setText(JTableEvento.getValueAt(a, 1).toString());
            FechaEvento.setText(JTableEvento.getValueAt(a, 2).toString());
            UbicacionEvento.setText(JTableEvento.getValueAt(a, 3).toString());
            TipoEvento.setSelectedItem(JTableEvento.getValueAt(a, 4).toString());
            PMenu.btnmodificar.setEnabled(true);
            PMenu.btnmodificar.setEnabled(true);

        }
    }

    public static void UpdateAction() {
        int a = JTableEvento.getSelectedRow();

        if (nombreEvento.getText().length() >= 1 && FechaEvento.getText().length() > 1 && 1 <= UbicacionEvento.getText().length()) {
            btnAgregarInternalFrameEvento(nombreEvento, FechaEvento, UbicacionEvento, TipoEvento, 1);

        } else {
            JOptionPane.showMessageDialog(null, "No deje campos vacios.");

        }
    }

    public static void btnAgregarInternalFrameEvento(JTextField nombre, JTextField Fecha, JTextField Ubicacion, JComboBox Tipo, int x) {
        int a = JTableEvento.getSelectedRow();
        event = new EventoImp();
        if (x == 0) {
            if (nombre.getText().length() >= 1 && Fecha.getText().length() > 1 && 1 <= Ubicacion.getText().length()) {

                evenMode = new EventoModel(nombre.getText(), Fecha.getText(), Ubicacion.getText(), Tipo.getSelectedItem().toString());
                event.save(evenMode);

            } else {
                JOptionPane.showMessageDialog(null, "No deje campos vacios.");
            }
        } else {
            evenMode = new EventoModel(nombre.getText(), Fecha.getText(), Ubicacion.getText(), Tipo.getSelectedItem().toString());

            if (a >= 0) {
                event.update(evenMode, Integer.parseInt(JTableEvento.getValueAt(a, 0).toString()));
            }

        }

    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vistas.PMenu.jInternalFrame2.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEventoActionPerformed
        // TODO add your handling code here:

        btnAgregarInternalFrameEvento(nombreEvento, FechaEvento, UbicacionEvento, TipoEvento, 0);
    }//GEN-LAST:event_AgregarEventoActionPerformed

    private void EditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEventoActionPerformed
        // TODO add your handling code here:

        UpdateAction();
    }//GEN-LAST:event_EditarEventoActionPerformed

    private void EditarEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEventoMouseClicked
        // TODO add your handling code heupre:
        //   Update_Delete(evt);
    }//GEN-LAST:event_EditarEventoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AgregarEvento;
    protected static javax.swing.JButton EditarEvento;
    public static javax.swing.JTextField FechaEvento;
    public static javax.swing.JComboBox<String> TipoEvento;
    public static javax.swing.JTextField UbicacionEvento;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanelEventoMante;
    public static javax.swing.JTextField nombreEvento;
    // End of variables declaration//GEN-END:variables
}
